package exceptionhandling;

public class check {

	static void Test() {
		throw new NullPointerException();
		
		
	}
	static void demo() {
		throw new ArithmeticException();
	}
	public static void main(String[]args) throws InterruptedException {
	int a=80;
	int b=0;


	System.out.println(c);
	
	System.out.println("main method is running");
		
		Test();
	//	demo();
		Thread.sleep(2000);
	}
	
}
